"""Initial migration: create research_papers, paper_qa_cache, job_status tables

Revision ID: 78200c22eb21
Revises: 
Create Date: 2025-12-10 17:55:52.430485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78200c22eb21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_status',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('arxiv_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_job_status_arxiv_id'), 'job_status', ['arxiv_id'], unique=False)
    op.create_index(op.f('ix_job_status_status'), 'job_status', ['status'], unique=False)
    op.create_table('research_papers',
    sa.Column('arxiv_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('published_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('vector_store_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cached_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cache_updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('last_modified_date <= cache_updated_at', name='check_dates'),
    sa.PrimaryKeyConstraint('arxiv_id')
    )
    op.create_index('idx_papers_cached', 'research_papers', ['cached_at'], unique=False)
    op.create_index('idx_papers_modified', 'research_papers', ['last_modified_date'], unique=False)
    op.create_index('idx_papers_status', 'research_papers', ['vector_store_status'], unique=False)
    op.create_index(op.f('ix_research_papers_title'), 'research_papers', ['title'], unique=False)
    op.create_table('paper_qa_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arxiv_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('question_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('citations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hallucination_score', sa.Float(), nullable=True),
    sa.Column('hallucination_risk', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('answer_relevancy_score', sa.Float(), nullable=True),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arxiv_id'], ['research_papers.arxiv_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arxiv_id', 'question_hash', name='uq_arxiv_question')
    )
    op.create_index('idx_qa_access', 'paper_qa_cache', ['access_count', 'last_accessed_at'], unique=False)
    op.create_index('idx_qa_arxiv', 'paper_qa_cache', ['arxiv_id'], unique=False)
    op.create_index('idx_qa_created', 'paper_qa_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_qa_cache_arxiv_id'), 'paper_qa_cache', ['arxiv_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_qa_cache_arxiv_id'), table_name='paper_qa_cache')
    op.drop_index('idx_qa_created', table_name='paper_qa_cache')
    op.drop_index('idx_qa_arxiv', table_name='paper_qa_cache')
    op.drop_index('idx_qa_access', table_name='paper_qa_cache')
    op.drop_table('paper_qa_cache')
    op.drop_index(op.f('ix_research_papers_title'), table_name='research_papers')
    op.drop_index('idx_papers_status', table_name='research_papers')
    op.drop_index('idx_papers_modified', table_name='research_papers')
    op.drop_index('idx_papers_cached', table_name='research_papers')
    op.drop_table('research_papers')
    op.drop_index(op.f('ix_job_status_status'), table_name='job_status')
    op.drop_index(op.f('ix_job_status_arxiv_id'), table_name='job_status')
    op.drop_table('job_status')
    # ### end Alembic commands ###
